### ISSUE TITLE
Remove from KB hotkey in Choose Translation dialog not working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [adapt-it/adaptit#56]
```
What steps will reproduce the problem?
1. When the Choose Translation dialog is open and an incorrect adaptation is 
selected, hold down the Alt key and type R
2.
3.

What is the expected output? What do you see instead?
I expected the warning about making the KB inconsistent to pop up, but the 
computer just beeped at me.

What version of the product are you using? On what operating system?
AI Wx 5.2.1 on Windows XP SP 3

Please provide any additional information below.

```

Original issue reported on code.google.com by `Jim.Henderson44` on 19 Jul 2010 at 8:18

Attachments:
- [Choose Translation dialog.PNG](https://storage.googleapis.com/google-code-attachments/adaptit/issue-56/comment-0/Choose Translation dialog.PNG)

**Comment by eb1** [comment]
Looks like this is still an issue in 6.5.8 / Windows 7.

Working: 
- Move Up, Move Down, Cancel

Not Working:
- Ok, Remove from KB

**Comment by adaptitbruce** [comment]
Hi Erik,
I just checked this in the ChooseTranslation dialog, I can tab from the
translation list to the buttons and to the New box at the bottom and
back to the left list. The only things tabbing does not shift the focus
to are the source box, and the references box. I don't think going to
those is relevant as both are read-only. I'm in AID, on my Win 7 computer.
I think this issue might be closed, right?

**Comment by pngbill** [comment]
Stale issue was resolved but never closed.
