### ISSUE TITLE
errors opening adapt it

### ISSUE THREAD

**Issue by aldoeri** [adapt-it/adaptit#67]
**Describe the bug**

**To Reproduce**
opening
![addaptit error](https://user-images.githubusercontent.com/25265688/200219942-682b353d-1f35-4f08-abe0-0cbdad9eac2d.jpg)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: e.g. Windows 10
 - Version[e.g. Adapt It 6.10.7  UNICODE

**Comment by eb1** [comment]
Hola @aldoeri -

Gracias por informarnos sobre este problema. 

Nos preguntamos si hay algún problema con la forma en que se localiza la estructura del directorio en Adapt It.  Puedes ver que Adapt It está buscando un directorio llamado "Documents", pero el directorio en la máquina se llama "Documentos" -- este podría ser el problema.

¿Puedes hacernos una prueba rápida en la computadora? ¿Podría crear manualmente un directorio en c:\Users\ALDO llamado "Documents" y luego iniciar Adapt It nuevamente? Eso nos diría si hay un problema con el nombre del directorio que Adapt It intenta crear al inicio.

**Comment by aldoeri** [comment]
i cant create a folder called users  because i have it in spanish  if i say
yes it dosent create the folder if I say no the name its stay as nueva
carpeta

**Comment by eb1** [comment]
Gracias por la respuesta! Creo que identificamos el problema; comenzaremos a trabajar en una versión para que la pruebes.

-Erik

**Comment by aldoeri** [comment]
> Gracias por la respuesta! Creo que identificamos el problema; comenzaremos a trabajar en una versión para que la pruebes.
> 
> -Erik

**Comment by aldoeri** [comment]
> > Gracias por la respuesta! Creo que identificamos el problema; comenzaremos a trabajar en una versión para que la pruebes.
> > -Erik

**Comment by aldoeri** [comment]
> > Gracias por la respuesta! Creo que identificamos el problema; comenzaremos a trabajar en una versión para que la pruebes.
> > -Erik 
it worked like these.  i have changed the language as EFS so it changed the documentos folder to document folder and it worked i will test the next version so i can change to  SFL

**Comment by aldoeri** [comment]
i erased adapt it WRX unicode and it dint worked even if i have english
configuration

**Comment by aldoeri** [comment]
still with errors 
![adaptit3](https://user-images.githubusercontent.com/25265688/200722510-4f1932dd-66dd-4be5-9f38-61219566e154.jpg)
