### ISSUE TITLE
Adaptit crash

### ISSUE THREAD

**Issue by Wild-Danel-Wild** [adapt-it/adaptit#68]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: Adaptit dos not start. Cannot access my working folders. 

**Expected behavior**

I used adaptit on other computers. Now program does not start on win 11. 

Error message annexed.
![Adaptit error](https://user-images.githubusercontent.com/124755566/217703908-56453439-6fc3-495b-b89c-701935c32180.jpg)

How can I start the program and access my working folders?

Daniel

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. Adapt It 6.8.2]

**Additional context**

**Comment by pngbill** [comment]
Hello Daniel,

Sorry for the delayed response. The error you received on startup 
indicates that Adapt It is not able to create and/or write to the "Adapt 
It Unicode Work" directory of your OneDrive partition. This could be the 
result of copying a whole "Adapt It Unicode Work" folder from a computer 
where a custom work folder location was previously set up, and the 
AI-BasicConfiguration.aic settings file remembers that location of a 
custom work folder location on a previous computer, that is not being 
used now on the Windows 11 computer. That is one possibility. Another 
possibility is that the OneDrive is write protected, or temporarily 
write protected, and Adapt It simply cannot write or create anything 
there. Please ensure that other computer programs can write to the same 
pathway location.

Adapt It normally expects its data to be found within an "Adapt It 
Unicode Work" folder in the Documents or "My Documents" folder of a 
Windows computer, which on your Windows 11 computer would have a typical 
path like this:

C:\Users\Daniel\Documents\Adapt It Unicode Work

The error message you give  below indicates that Adapt It expects to 
find its data in a *non-standard custom work folder* using the OneDrive 
directory at a path like this:

C:\Users\daniel\OneDrive\2014-01-25\Adapt It Unicode Work

Is the above pathway (that is used in the error message) the same 
pathway that was used on other computers? That is, did the other 
computers also use a ...\OneDrive\2014-01-25\... pathway to the "Adapt 
It Unicode Work" directory? Or, is the message referring to a custom 
location that you are using now on the Windows 11 computer system?

What to do to solve the issue depends on whether the pathways to the 
"Adapt It Unicode Work" folders are the same or different from what you 
used on the other computers. When copying the contents of the "Adapt It 
Unicode Work" folders from one computer to another computer, Adapt It 
will expect that generally, the two computers will have their Adapt It 
data in similar default pathways for default data folder locations. 
However, I'm wondering if the data locations are *not* default locations 
- either for the previous computers, or now for the Win 11 computer, but 
are or were a custom folder location on one or both computers?

We need to know which situation you have there. The path referenced in 
the error message appears to be a non-default location. But it is not 
clear if that is a remembered path from the other computers, or is a new 
custom path you wish to use on the Windows 11 computer.

Please tell us which situation you have.

In the mean time there are a couple things you might try on the new 
Windows 11 computer to get Adapt It up and running:

1. First upgrade to the newest version of Adapt It that is available 
from https://www.adapt-it.org. The latest version is version 6.10.7. 
Installing a newer version won't remove any of your data. Note that 
within the next few weeks a newer version 6.11.0 will be released. The 
newer 6.11.0 version is not likely to solve your issue however, if you 
are wanting to use a custom work folder with OneDrive.

2. If the latest version of Adapt It has the same startup problem, you 
could try holding down the SHIFT key while starting up the Adapt It 
program. This allows Adapt It to bypass a number of settings within its 
basic configuration file named AI-BasicConfiguration.aic settings file. 
Once Adapt It is running you could then try to set up a  custom work 
folder location that can point to the "Adapt It Unicode Work" folder in 
its custom location - as indicated in the error message below.

Setting up Adapt It with a *custom work folder* to utilize a folder 
located at C:\Users\daniel\OneDrive\2014-01-25\Adapt It Unicode Work" 
can be done as follows once Adapt It is able to run up to its initial 
"Choose a Project" wizard page:

* Click "Cancel" at the initial "Choose a Project" startup wizard page.

* Make the "Administrator" menu visible. It is normally hidden and 
accessible via password.  To get access to the "Administrator" menu, you 
can make it visible by first selecting the "*View*" > "*Show 
Administrator Menu... (password protected)*" item. It will ask you for 
the administrator password. The general password that always works is 
*admin* . Once the "Administrator" menu is visible on the right end of 
Adapt It's menu bar, select the "*Administrator" > "Custom Work Folder 
Location*" item and put the pathway to the folder where Adapt It is 
looking its work folder - as shown in the error message.

With the information you've provided, that's about all I can suggest at 
this point. Please feel free to let us know how it goes.

For continued correspondence, the best way to get a timely response from 
us is via email message, sent to both ***@***.**** and also to 
***@***.****.

Blessings,

Bill

**Comment by Wild-Danel-Wild** [comment]
Hi Bill,
Thank you for your help. Finally I figured out that Windows 11 has a stupid security feature added .The Windows security  blocked Adaptit from starting, and it also did block access to OneDrive. Of course the Adaptit folders never had been there. I could start Adaptit now, and I can access the correct folders again.

So every `unknown` program is blocked and has to be manually marked as `allowed`

Daniel

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Bill ***@***.***>
Enviado:sexta-feira, 10 de fevereiro de 2023 18:40
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [adapt-it/adaptit] Adaptit crash (Issue #68)

Hello Daniel,

Sorry for the delayed response. The error you received on startup
indicates that Adapt It is not able to create and/or write to the "Adapt
It Unicode Work" directory of your OneDrive partition. This could be the
result of copying a whole "Adapt It Unicode Work" folder from a computer
where a custom work folder location was previously set up, and the
AI-BasicConfiguration.aic settings file remembers that location of a
custom work folder location on a previous computer, that is not being
used now on the Windows 11 computer. That is one possibility. Another
possibility is that the OneDrive is write protected, or temporarily
write protected, and Adapt It simply cannot write or create anything
there. Please ensure that other computer programs can write to the same
pathway location.

Adapt It normally expects its data to be found within an "Adapt It
Unicode Work" folder in the Documents or "My Documents" folder of a
Windows computer, which on your Windows 11 computer would have a typical
path like this:

C:\Users\Daniel\Documents\Adapt It Unicode Work

The error message you give  below indicates that Adapt It expects to
find its data in a *non-standard custom work folder* using the OneDrive
directory at a path like this:

C:\Users\daniel\OneDrive\2014-01-25\Adapt It Unicode Work

Is the above pathway (that is used in the error message) the same
pathway that was used on other computers? That is, did the other
computers also use a ...\OneDrive\2014-01-25\... pathway to the "Adapt
It Unicode Work" directory? Or, is the message referring to a custom
location that you are using now on the Windows 11 computer system?

What to do to solve the issue depends on whether the pathways to the
"Adapt It Unicode Work" folders are the same or different from what you
used on the other computers. When copying the contents of the "Adapt It
Unicode Work" folders from one computer to another computer, Adapt It
will expect that generally, the two computers will have their Adapt It
data in similar default pathways for default data folder locations.
However, I'm wondering if the data locations are *not* default locations
- either for the previous computers, or now for the Win 11 computer, but
are or were a custom folder location on one or both computers?

We need to know which situation you have there. The path referenced in
the error message appears to be a non-default location. But it is not
clear if that is a remembered path from the other computers, or is a new
custom path you wish to use on the Windows 11 computer.

Please tell us which situation you have.

In the mean time there are a couple things you might try on the new
Windows 11 computer to get Adapt It up and running:

1. First upgrade to the newest version of Adapt It that is available
from https://www.adapt-it.org. The latest version is version 6.10.7.
Installing a newer version won't remove any of your data. Note that
within the next few weeks a newer version 6.11.0 will be released. The
newer 6.11.0 version is not likely to solve your issue however, if you
are wanting to use a custom work folder with OneDrive.

2. If the latest version of Adapt It has the same startup problem, you
could try holding down the SHIFT key while starting up the Adapt It
program. This allows Adapt It to bypass a number of settings within its
basic configuration file named AI-BasicConfiguration.aic settings file.
Once Adapt It is running you could then try to set up a  custom work
folder location that can point to the "Adapt It Unicode Work" folder in
its custom location - as indicated in the error message below.

Setting up Adapt It with a *custom work folder* to utilize a folder
located at C:\Users\daniel\OneDrive\2014-01-25\Adapt It Unicode Work"
can be done as follows once Adapt It is able to run up to its initial
"Choose a Project" wizard page:

* Click "Cancel" at the initial "Choose a Project" startup wizard page.

* Make the "Administrator" menu visible. It is normally hidden and
accessible via password.  To get access to the "Administrator" menu, you
can make it visible by first selecting the "*View*" > "*Show
Administrator Menu... (password protected)*" item. It will ask you for
the administrator password. The general password that always works is
*admin* . Once the "Administrator" menu is visible on the right end of
Adapt It's menu bar, select the "*Administrator" > "Custom Work Folder
Location*" item and put the pathway to the folder where Adapt It is
looking its work folder - as shown in the error message.

With the information you've provided, that's about all I can suggest at
this point. Please feel free to let us know how it goes.

For continued correspondence, the best way to get a timely response from
us is via email message, sent to both ***@***.**** and also to
***@***.****.

Blessings,

Bill

**Comment by pngbill** [comment]
Hi Daniel,

Thank you for telling us what the problem was and how you resolved it!

Blessings,

Bill - for the Adapt It team
